import type {
  CommandBlock,
  CrewMate,
  FruitPower,
  MissionDefinition,
  MissionNode,
  PlannedCommand,
} from "./types";

const makeCommand = (
  instanceId: string,
  templateId: string,
  partial: Partial<PlannedCommand> = {},
): PlannedCommand => ({
  instanceId,
  templateId,
  type:
    templateId === "repeat"
      ? "loop"
      : templateId === "if"
        ? "condition"
        : "action",
  ...partial,
});

export const commandLibrary: Record<string, CommandBlock> = {
  sail: {
    id: "sail",
    type: "action",
    label: "Sail",
    shortLabel: "Sail",
    accent: "blue",
    description: "Move one water tile forward.",
    defaultAction: "sail",
  },
  "turn-left": {
    id: "turn-left",
    type: "action",
    label: "Turn Left",
    shortLabel: "Left",
    accent: "teal",
    description: "Turn the bow to port.",
    defaultAction: "turn-left",
  },
  "turn-right": {
    id: "turn-right",
    type: "action",
    label: "Turn Right",
    shortLabel: "Right",
    accent: "teal",
    description: "Turn the bow to starboard.",
    defaultAction: "turn-right",
  },
  dodge: {
    id: "dodge",
    type: "action",
    label: "Dodge",
    shortLabel: "Dodge",
    accent: "coral",
    description: "Slide into a safe lane when trouble is ahead.",
    defaultAction: "dodge",
  },
  fire: {
    id: "fire",
    type: "action",
    label: "Fire",
    shortLabel: "Fire",
    accent: "gold",
    description: "Splash an enemy in front of the ship.",
    defaultAction: "fire",
  },
  collect: {
    id: "collect",
    type: "action",
    label: "Collect",
    shortLabel: "Collect",
    accent: "mint",
    description: "Pick up a treasure on the ship tile.",
    defaultAction: "collect",
  },
  talk: {
    id: "talk",
    type: "action",
    label: "Talk",
    shortLabel: "Talk",
    accent: "plum",
    description: "Invite a waiting crew mate aboard.",
    defaultAction: "talk",
  },
  repeat: {
    id: "repeat",
    type: "loop",
    label: "Repeat",
    shortLabel: "Repeat",
    accent: "sunset",
    description: "Repeat one action two or three times.",
    defaultCount: 2,
    defaultAction: "sail",
    actionOptions: ["sail", "fire", "collect", "talk"],
  },
  if: {
    id: "if",
    type: "condition",
    label: "If",
    shortLabel: "If",
    accent: "storm",
    description: "Watch the sea, then do the matching move.",
    defaultCondition: "enemyAhead",
    defaultAction: "fire",
    conditionOptions: [
      "enemyAhead",
      "obstacleAhead",
      "treasureHere",
      "crewHere",
    ],
    actionOptions: ["fire", "dodge", "collect", "talk"],
  },
};

export const crewMates: Record<string, CrewMate> = {
  sunny: {
    id: "sunny",
    name: "Sunny",
    title: "Lookout",
    description: "Adds a brighter hint when a ship bumps into trouble.",
    passiveType: "hint",
  },
  pebble: {
    id: "pebble",
    name: "Pebble",
    title: "Quartermaster",
    description: "Finds one bonus coin whenever a mission is cleared.",
    passiveType: "gold",
  },
};

export const fruitPowers: Record<string, FruitPower> = {
  emberfruit: {
    id: "emberfruit",
    name: "Ember Fruit",
    title: "Long Splash",
    description: "Fire can splash enemies two tiles away.",
    modifier: "extraFireRange",
  },
};

export const missionNodes: MissionNode[] = [
  {
    id: "tutorial-cove",
    missionId: "tutorial-cove",
    label: "Tutorial Cove",
    sea: "Starter Cove",
    x: 12,
    y: 78,
    difficulty: "cove",
    preview: "Sail to the first chest and learn how the queue works.",
    rewards: { gold: 6, stars: 1, unlockCommandIds: ["fire"] },
    unlockMissionIds: [],
  },
  {
    id: "spark-shoals",
    missionId: "spark-shoals",
    label: "Spark Shoals",
    sea: "Sea 1",
    x: 30,
    y: 64,
    difficulty: "breeze",
    preview: "Use sequencing and a splash cannon to clear a lane.",
    rewards: { gold: 10, stars: 2, crewId: "sunny", unlockCommandIds: ["dodge"] },
    unlockMissionIds: ["tutorial-cove"],
  },
  {
    id: "current-crescent",
    missionId: "current-crescent",
    label: "Current Crescent",
    sea: "Sea 2",
    x: 51,
    y: 48,
    difficulty: "breeze",
    preview: "Meet repeat blocks and surf a long stream of shiny water.",
    rewards: { gold: 14, stars: 2, unlockCommandIds: ["repeat"] },
    unlockMissionIds: ["spark-shoals"],
  },
  {
    id: "coral-lookout",
    missionId: "coral-lookout",
    label: "Coral Lookout",
    sea: "Sea 3",
    x: 71,
    y: 36,
    difficulty: "brave",
    preview: "Teach the crew to react with if-then plans.",
    rewards: { gold: 18, stars: 3, fruitPowerId: "emberfruit", unlockCommandIds: ["if", "talk"] },
    unlockMissionIds: ["current-crescent"],
  },
  {
    id: "treasure-isle",
    missionId: "treasure-isle",
    label: "Treasure Isle",
    sea: "Final",
    x: 87,
    y: 22,
    difficulty: "captain",
    preview: "Mix repeat and if blocks to reach the glowing grand prize.",
    rewards: { gold: 24, stars: 3, crewId: "pebble", unlockCommandIds: [] },
    unlockMissionIds: ["coral-lookout"],
  },
];

export const missions: Record<string, MissionDefinition> = {
  "tutorial-cove": {
    id: "tutorial-cove",
    nodeId: "tutorial-cove",
    label: "Tutorial Cove",
    sea: "Starter Cove",
    briefing: "Line up your first sailing plan and scoop up the chest.",
    tutorial: "Try adding Sail, Sail, Sail, Collect, Sail, Sail.",
    width: 6,
    height: 3,
    start: {
      position: { x: 0, y: 1 },
      facing: "east",
    },
    goal: { x: 5, y: 1 },
    objective: {
      primary: "Collect the chest and sail to the lighthouse.",
      short: "Collect chest, then reach the lighthouse.",
    },
    palette: ["sail", "collect"],
    requiredTileIds: ["cove-chest"],
    reward: { gold: 6, stars: 1, unlockCommandIds: ["fire"] },
    tiles: [
      {
        id: "cove-chest",
        kind: "treasure",
        position: { x: 3, y: 1 },
        label: "Chest",
        active: true,
      },
    ],
    suggestedQueue: [
      makeCommand("cove-1", "sail", { action: "sail" }),
      makeCommand("cove-2", "sail", { action: "sail" }),
      makeCommand("cove-3", "sail", { action: "sail" }),
      makeCommand("cove-4", "collect", { action: "collect" }),
      makeCommand("cove-5", "sail", { action: "sail" }),
      makeCommand("cove-6", "sail", { action: "sail" }),
    ],
  },
  "spark-shoals": {
    id: "spark-shoals",
    nodeId: "spark-shoals",
    label: "Spark Shoals",
    sea: "Sea 1",
    briefing: "One splashy gull-bot blocks the gold lane. Fire first, then sail.",
    tutorial: "If a crab skiff is in front, Fire before you Sail.",
    width: 7,
    height: 3,
    start: {
      position: { x: 0, y: 1 },
      facing: "east",
    },
    goal: { x: 6, y: 1 },
    objective: {
      primary: "Clear the enemy, collect the chest, and sail home.",
      short: "Fire, collect, and reach the dock.",
    },
    palette: ["fire", "sail", "collect"],
    requiredTileIds: ["spark-chest"],
    reward: { gold: 10, stars: 2, crewId: "sunny", unlockCommandIds: ["dodge"] },
    tiles: [
      {
        id: "spark-enemy",
        kind: "enemy",
        position: { x: 1, y: 1 },
        label: "Skiff",
        active: true,
      },
      {
        id: "spark-chest",
        kind: "treasure",
        position: { x: 4, y: 1 },
        label: "Sun Chest",
        active: true,
      },
    ],
    suggestedQueue: [
      makeCommand("spark-1", "fire", { action: "fire" }),
      makeCommand("spark-2", "sail", { action: "sail" }),
      makeCommand("spark-3", "sail", { action: "sail" }),
      makeCommand("spark-4", "sail", { action: "sail" }),
      makeCommand("spark-5", "sail", { action: "sail" }),
      makeCommand("spark-6", "collect", { action: "collect" }),
      makeCommand("spark-7", "sail", { action: "sail" }),
      makeCommand("spark-8", "sail", { action: "sail" }),
    ],
  },
  "current-crescent": {
    id: "current-crescent",
    nodeId: "current-crescent",
    label: "Current Crescent",
    sea: "Sea 2",
    briefing: "The sea sparkles in a long ribbon. Use Repeat to speed through it.",
    tutorial: "Try Repeat Sail 4, Collect, Repeat Sail 3.",
    width: 8,
    height: 5,
    start: {
      position: { x: 0, y: 2 },
      facing: "east",
    },
    goal: { x: 7, y: 2 },
    objective: {
      primary: "Use Repeat to cross the crescent and grab the bright chest.",
      short: "Repeat Sail, Collect, Repeat Sail.",
    },
    palette: ["sail", "collect", "repeat"],
    requiredTileIds: ["current-chest"],
    reward: { gold: 14, stars: 2, unlockCommandIds: ["repeat"] },
    tiles: [
      {
        id: "current-chest",
        kind: "treasure",
        position: { x: 4, y: 2 },
        label: "Moon Chest",
        active: true,
      },
      {
        id: "current-wave-1",
        kind: "current",
        position: { x: 2, y: 2 },
        label: "Current",
        active: true,
      },
      {
        id: "current-wave-2",
        kind: "current",
        position: { x: 3, y: 2 },
        label: "Current",
        active: true,
      },
    ],
    suggestedQueue: [
      makeCommand("current-1", "repeat", {
        count: 4,
        action: "sail",
      }),
      makeCommand("current-2", "collect", { action: "collect" }),
      makeCommand("current-3", "repeat", {
        count: 3,
        action: "sail",
      }),
    ],
  },
  "coral-lookout": {
    id: "coral-lookout",
    nodeId: "coral-lookout",
    label: "Coral Lookout",
    sea: "Sea 3",
    briefing: "Teach the crew to react when danger shows up in front of the bow.",
    tutorial: "Use If Enemy then Fire before sailing into the lookout lane.",
    width: 8,
    height: 3,
    start: {
      position: { x: 0, y: 1 },
      facing: "east",
    },
    goal: { x: 7, y: 1 },
    objective: {
      primary: "React with If Enemy, then grab the coral treasure.",
      short: "If Enemy Fire, Collect, then dock.",
    },
    palette: ["if", "fire", "sail", "collect"],
    requiredTileIds: ["coral-chest"],
    reward: {
      gold: 18,
      stars: 3,
      fruitPowerId: "emberfruit",
      unlockCommandIds: ["if", "talk"],
    },
    tiles: [
      {
        id: "coral-enemy",
        kind: "enemy",
        position: { x: 1, y: 1 },
        label: "Lookout Skiff",
        active: true,
      },
      {
        id: "coral-chest",
        kind: "treasure",
        position: { x: 5, y: 1 },
        label: "Coral Chest",
        active: true,
      },
    ],
    suggestedQueue: [
      makeCommand("coral-1", "if", {
        condition: "enemyAhead",
        thenAction: "fire",
      }),
      makeCommand("coral-2", "repeat", {
        count: 5,
        action: "sail",
      }),
      makeCommand("coral-3", "collect", { action: "collect" }),
      makeCommand("coral-4", "repeat", {
        count: 2,
        action: "sail",
      }),
    ],
  },
  "treasure-isle": {
    id: "treasure-isle",
    nodeId: "treasure-isle",
    label: "Treasure Isle",
    sea: "Final",
    briefing: "The last voyage needs smart reactions and a repeated push through open water.",
    tutorial: "If Obstacle then Dodge, Repeat Sail, If Enemy then Fire, Talk, then sail home.",
    width: 10,
    height: 5,
    start: {
      position: { x: 0, y: 3 },
      facing: "east",
    },
    goal: { x: 9, y: 2 },
    objective: {
      primary: "Dodge the reef, splash the boss skiff, recruit the island guide, and reach the treasure.",
      short: "If Obstacle, Repeat Sail, If Enemy, Talk, then finish.",
    },
    palette: ["sail", "dodge", "fire", "talk", "repeat", "if"],
    requiredTileIds: ["isle-guide"],
    reward: { gold: 24, stars: 3, crewId: "pebble", unlockCommandIds: [] },
    tiles: [
      {
        id: "isle-reef",
        kind: "obstacle",
        position: { x: 2, y: 3 },
        label: "Reef",
        active: true,
      },
      {
        id: "isle-boss",
        kind: "enemy",
        position: { x: 7, y: 2 },
        label: "Boss Skiff",
        active: true,
      },
      {
        id: "isle-guide",
        kind: "crew",
        position: { x: 8, y: 2 },
        label: "Island Guide",
        active: true,
      },
    ],
    suggestedQueue: [
      makeCommand("isle-1", "sail", { action: "sail" }),
      makeCommand("isle-2", "if", {
        condition: "obstacleAhead",
        thenAction: "dodge",
      }),
      makeCommand("isle-3", "repeat", {
        count: 5,
        action: "sail",
      }),
      makeCommand("isle-4", "if", {
        condition: "enemyAhead",
        thenAction: "fire",
      }),
      makeCommand("isle-5", "sail", { action: "sail" }),
      makeCommand("isle-6", "sail", { action: "sail" }),
      makeCommand("isle-7", "talk", { action: "talk" }),
      makeCommand("isle-8", "sail", { action: "sail" }),
    ],
  },
};

export const orderedMissionIds = missionNodes.map((node) => node.missionId);
